# Generated by Django 3.1.7 on 2021-05-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='unpickednames',
            name='pickedName',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
